# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

# This makes Click behave itself.
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

Lint_task:
  container:
    image: python:3.8-slim
  install_script:
    - pip install -U --upgrade-strategy eager pip 'setuptools>42'
    - pip install .
    - pip install .[testing]
  script:
    - pylint --version
    - bork run lint

Zipapp_bootstrap_task:
  container:
    matrix:
      image: python:3.7-slim
      image: python:3.8-slim
      image: python:3.9-slim
  setup_script:
    - pip install -U --upgrade-strategy eager pip 'setuptools>42'
    - cp -r . /tmp/bork-pristine
    - cp -r /tmp/bork-pristine /tmp/pass1
    - cp -r /tmp/bork-pristine /tmp/pass2
    - cp -r /tmp/bork-pristine /tmp/pass3
  # Make sure Bork can build itself.
  pass_1_script:
    - cd /tmp/pass1
    - python3 --version
    - pip install . .[testing]
    - bork build
  # Make sure the Bork zipapp from Pass 1 can build Bork.
  pass_2_script:
    - cd /tmp/pass2
    - cp /tmp/pass1/dist/bork-*.pyz /tmp/bork-pass1.pyz
    - python3 /tmp/bork-pass1.pyz build
  # Make sure the Bork zipapp built from Pass 2 can build Bork.
  # ime with other self-building software, this is prone to blowing up.
  pass_3_script:
    - cd /tmp/pass3
    - cp /tmp/pass2/dist/bork-*.pyz /tmp/bork-pass2.pyz
    - python3 /tmp/bork-pass2.pyz build
    - '[ -e ./dist/bork-*.pyz ]'


Linux_task:
  container:
    matrix:
      - image: python:3.6-slim
      - image: python:3.7-slim
      - image: python:3.8-slim
      - image: python:3.9-slim
  install_script:
    - apt-get update
    - apt-get install -y git
    - pip install -U --upgrade-strategy eager pip 'setuptools>42'
    - pip install . .[testing]
  script:
    - python3 --version
    - bork run test

macOS_task:
  osx_instance:
    image: catalina-xcode
  env:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    PATH: ${HOME}/.pyenv/shims:${PATH}
    matrix:
      - PYTHON: 3.6.9
      - PYTHON: 3.7.9
      - PYTHON: 3.8.6
      - PYTHON: 3.9.0
  install_script:
    # Per the pyenv homebrew recommendations.
    #  https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    - brew install openssl readline pyenv git
    - pyenv install ${PYTHON}
    - pyenv global ${PYTHON}
    - pyenv rehash
    - pip install -U --upgrade-strategy eager pip 'setuptools>42'
    - pip install -e .[testing]
  script:
    - python3 --version
    - bork run test

FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-12-1-snap
  env:
    matrix:
      - PYTHON: 3.6
      - PYTHON: 3.7
      - PYTHON: 3.8
  install_script:
    - PY=`echo $PYTHON | tr -d '.'`
    - pkg install -y python${PY} py${PY}-setuptools git
    - python${PYTHON} -m ensurepip
    - python${PYTHON} -m pip install -U --upgrade-strategy eager pip 'setuptools>42'
    - python${PYTHON} -m pip install -e .[testing_only]
  script:
    - python${PYTHON} --version
    - bork run test

# Windows_task:
#   allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
#   windows_container:
#     os_version: 2019
#     matrix:
#       - image: python:3.6-windowsservercore-1809
#       - image: python:3.7-windowsservercore-1809
#       - image: python:3.8-rc-windowsservercore-1809

#   install_script:
#     - C:\Python\python.exe -m pip install -e .[testing]
#   script:
#     - C:\Python\python.exe --version
#     - C:\Python\python.exe -m pytest --verbose

# If bork/version.py is modified on the master branch, make a release.
Release_task:
  only_if: "changesInclude('bork/version.py') && $BRANCH == 'master' && $CIRRUS_CRON == ''"
  depends_on:
    - Lint
    - Zipapp_bootstrap
    - Linux
    - macOS
    - FreeBSD
    #- Windows
  env:
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: ENCRYPTED[00007524e18bea7b59efea288653efa57b1dbd235ed8af00cc325febfc9076631a2bf58ed330d8fa7ca057adb81579b0]
    BORK_GITHUB_TOKEN: ENCRYPTED[cc80f90b8db1cbe53aabf4f50bf73331c88ea3e1b5412bb0f7bc264bd233f23bf8df4fc2b4c41f87ec07310d63619801]
  container:
    image: python:3.8-slim
  install_script:
    - apt-get update
    - apt-get install -y git
    - pip install -U --upgrade-strategy eager pip 'setuptools>42'
    - pip3 install . .[testing]
  build_script:
    - bork clean
    - bork build
  test_script:
    - bork run test
  release_script:
    - bork release

# If there's a new tag, which should only happen after a successful release
# to PyPi, publish an image on Docker Hub.
docker_builder:
  only_if: $CIRRUS_TAG != ''
  name: "Release on Docker Hub"
  depends_on:
    - Release
  env:
    DOCKER_USERNAME: ENCRYPTED[a957943032559f0859a16a4421bc3602338080e6d9ce63a980db4fd34dbdc2afbe3a20c620139c669182eced4211a515]
    DOCKER_PASSWORD: ENCRYPTED[dd7f31d490b645298258ac9ec78ac3a7e034e8bfcf8fbfec0137787eef3934e01a42ef3b5eda42b1b1f7a3296fae619e]
  delay_script: sleep 10 # Attempt to ensure it is available via pip.
  build_script:
    - docker build --tag duckinator/bork:${CIRRUS_TAG} --tag duckinator/bork:latest --build-arg "VERSION=$(echo $CIRRUS_TAG | sed 's/^v//')" .
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_tag_script: docker push duckinator/bork:$CIRRUS_TAG
  push_latest_script:
    - if grep -qE "^__version__\s+=\s+['\"]([0-9.]+)['\"]$" bork/version.py; then docker push duckinator/bork:latest; fi
