version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3"

python:
  install:
    - requirements: docs-requirements.txt

sphinx:
  configuration: docs/source/conf.py

# Build PDF & ePub versions of docs.
formats:
  - epub
  - pdf
