site_name: bork
site_description: "Documentation for Bork, the build and release management tool for Python."
repo_url: https://github.com/duckinator/bork
edit_uri: blob/main/docs/

nav:
- Home: index.md
- API: api.md

plugins:
- search
- mkdocstrings

theme:
  name: readthedocs
  highlightjs: true
